os: Visual Studio 2017

environment:
  appx_ver: 21.7.16.0
  wsldl_ver: 21071600
  fs_ver: 21071500
  pfx_secret:
    secure: XlXaj3gSIBd9YNKz8zuI9dtBJIoq+TTwj3HkWyyXzUTuk5b/Ur7OY2abhV9zNacetbLJKfKQSYJQLIUF9uNAFHMZoDdAKK6rq2Uzii+JB3KBaWg7w5iIfdJKD6/LD3TYjVUzQPYzEGMC45s6adk8ru3CR2kDJzhvrvqf93pL55E=

install:
  - cmd: git submodule init
  - cmd: git submodule update
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt appx\wsldl-AppX\wsldl-AppX_TemporaryKey.pfx.enc -secret %pfx_secret%

before_build:
  - ps: Invoke-WebRequest https://github.com/yuk7/wsldl/releases/download/${env:wsldl_ver}/icons.zip -OutFile icons.zip -UseBasicParsing
  - ps: Expand-Archive icons.zip -DestinationPath appx\wsldl-AppX\
  - ps: Invoke-WebRequest https://github.com/yuk7/ArchWSL-FS/releases/download/${env:fs_ver}/rootfs.tar.gz -OutFile appx\wsldl-AppX\rootfs.tar.gz -UseBasicParsing
  - ps: $vtxt = 'Version="'+${env:appx_ver}+'"'
  - ps: $file_contents = $(Get-Content "appx\wsldl-AppX\package.appxmanifest") -replace 'Version="19.0.0.0"',$vtxt
  - ps: $file_contents | Out-File "appx\wsldl-AppX\package.appxmanifest" -Encoding utf8 

build_script:
  - cmd: msbuild appx\wsldl-AppX.sln /p:Configuration=Release;AppxBundle=Never

after_build:
  - ps: New-Item out -ItemType Directory
  - ps: Move-Item appx\wsldl-AppX\AppPackages\wsldl-AppX_${env:appx_ver}_x64_Test\wsldl-AppX_${env:appx_ver}_x64.appx out\ArchWSL-AppX_${env:appx_ver}_x64.appx
  - ps: Move-Item appx\wsldl-AppX\AppPackages\wsldl-AppX_${env:appx_ver}_x64_Test\wsldl-AppX_${env:appx_ver}_x64.cer out\ArchWSL-AppX_${env:appx_ver}_x64.cer

artifacts:
  - path: 'out\*.appx'
  - path: 'out\*.cer'

deploy:
 - provider: GitHub
   auth_token:
     secure: 4E1LKf0gRUSciyoPkXps27bqYlHGeWJa0PwFdApSy+rHaHq/p3d9k9NOBNYivLEA
   on:
     appveyor_repo_tag: true 
